language: node_js
node_js:
    - 16

services:
    - docker

# Pre-testing installs
install:
    - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
    - echo "no tests"

script:
    - docker --version # print the version for logging
    # build:
    - docker build -t udagram-api-feed ./udagram-api-feed
    - docker build -t udagram-api-user ./udagram-api-user
    - docker build -t udagram-frontend ./udagram-frontend
    - docker build -t udagram-reverseproxy ./udagram-reverseproxy

    - docker pull
    # tag:
    - docker tag udagram-api-feed johnnyrico97/udagram-api-feed:v5
    - docker tag udagram-api-user johnnyrico97/udagram-api-user:v5
    - docker tag udagram-frontend johnnyrico97/udagram-frontend:v5
    - docker tag udagram-reverseproxy johnnyrico97/udagram-reverseproxy:v5

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    # push:
    - docker push johnnyrico97/udagram-api-feed:v5
    - docker push johnnyrico97/udagram-api-user:v5
    - docker push johnnyrico97/udagram-frontend:v5
    - docker push johnnyrico97/udagram-reverseproxy:v5
