apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend
    labels:
        app: frontend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: frontend
    template:
        metadata:
            labels:
                app: frontend
        spec:
            containers:
                - name: frontend
                  image: johnnyrico97/udagram-frontend:v7
                  imagePullPolicy: Always
                  envFrom:
                      - secretRef:
                            name: env-secret
                      - configMapRef:
                            name: env-config
                      - secretRef:
                            name: aws-secret
                  ports:
                      - containerPort: 80
