apiVersion: apps/v1
kind: Deployment
metadata:
    name: reverseproxy
    labels:
        app: reverseproxy
spec:
    selector:
        matchLabels:
            service: reverseproxy
    replicas: 1
    template:
        metadata:
            labels:
                service: reverseproxy
        spec:
            containers:
                - image: johnnyrico97/udagram-reverseproxy:v13
                  name: reverseproxy
                  imagePullPolicy: Always
                  envFrom:
                      - secretRef:
                            name: env-secret
                      - configMapRef:
                            name: env-config
                      - secretRef:
                            name: aws-secret
                  ports:
                      - containerPort: 8080
