apiVersion: v1
kind: Service
metadata:
    labels:
        service: reverseproxy
    name: reverseproxy
spec:
    ports:
        - name: '8080'
          port: 8080
          targetPort: 8080
          protocol: TCP
    selector:
        service: reverseproxy
